/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.4
 * Generated at: 2018-06-08 09:54:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import es.portanode.util.Calendario;
import es.portanode.util.Singleton;

public final class Autenticacion_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/cabeceraAuth.jsp", Long.valueOf(1528450515441L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("es.portanode.util.Calendario");
    _jspx_imports_classes.add("es.portanode.util.Singleton");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\r\n");
      out.write("\r\n");

  try{
    String mensaje = (String)request.getAttribute("Mensaje");
if(mensaje == null)
	mensaje = "";
    String subtitulo1 = new String("Autenticación");

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("   <title>Validaci&oacute;n de Usuarios</title>\r\n");
      out.write("<link href=\"estilos/estilos.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<SCRIPT Language=\"javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function Enviar(){\r\n");
      out.write("\r\n");
      out.write("\tvar f = document.theForm;\r\n");
      out.write("\tif(f.usuario.value==\"\"){\r\n");
      out.write("\t\talert(\"Introduza su Nombre de Usuario\");\r\n");
      out.write("\t\tf.usuario.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t/*if(f.password.value==\"\"){\r\n");
      out.write("\t\talert(\"Introduzca su Contraseña\")\r\n");
      out.write("\t\tf.password.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}*/\r\n");
      out.write("\r\n");
      out.write("\tf.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function detectarEnter(e) {\r\n");
      out.write("\tvar ieKey=event.keyCode;\r\n");
      out.write("    if(ieKey==13)\r\n");
      out.write("    Enviar();\r\n");
      out.write("}\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("<link href=\"estilos/estilos.css\" rel=\"stylesheet\" type=\"text/css\"> </head>\r\n");
      out.write("\r\n");
      out.write("<!-- link=\"#666666\" alink=\"#000000\" vlink=\"#008080\" -->\r\n");
      out.write("<BODY leftMargin=0 topMargin=0 marginheight=\"0\" marginwidth=\"0\">\r\n");
      out.write("<!-- Insercion de Cabecera -->\r\n");
      out.write("  ");

    String imagen = (String) request.getAttribute("OperadorConexion");
    if(imagen==null) imagen = (String) request.getAttribute("OperadorConectado");
    if(imagen==null)  imagen="";
    String logo = "";
    if (imagen.equals("")){
       logo = "<img src='images/telefono.jpg' name='logotipo' width='90' height='56'>";
    }
    else{
       logo = "<img src='images/"+imagen+".gif' name='logotipo' ALT='Operador' width='161' height='56'>";
    }
  
      out.write("\r\n");
      out.write("  <!-- Fin Insercion de Cabecera -->\r\n");
      out.write("<table width=\"100%\" height=\"56\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td class='celdalineaabajo'>");
      out.print(logo);
      out.write("</td>\r\n");
      out.write("    <td class='celdalineaabajo' colspan=\"2\" align=\"center\">\r\n");
      out.write("      <img src='images/portanode.png' name='logotipo' ALT='Operador'>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td align=\"right\" class='celdalineaabajo'>\r\n");
      out.write("      <font class=\"texto3\">");
      out.print(subtitulo1);
      out.write("</font>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("var totalHeight=window.screen.availHeight - 211;\r\n");
      out.write("var tabla=\"<table width='100%' height='\" + totalHeight + \"' border='0' cellpadding='0' cellspacing='0'>\";\r\n");
      out.write("document.write(tabla);\r\n");
      out.write("</script>\r\n");
      out.write("  <TBODY>\r\n");
      out.write("  <TR>\r\n");
      out.write("    <td width=\"10\" class=\"Fondoverdederecha\">\r\n");
      out.write("       &nbsp;\r\n");
      out.write("    </td>\r\n");
      out.write("    <TD vAlign=top width=\"180\" class=\"celdalineaderecha\">\r\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu_vacio.jsp", out, true);
      out.write("\r\n");
      out.write("    </TD><!-- InstanceBeginEditable name=\"contenido\" -->\r\n");
      out.write("    <TD class=Titulo vAlign=top align=middle background=\"images/fondocentro.gif\">\r\n");
      out.write("        <center>\r\n");
      out.write("         <font class=\"textonegro\">VALIDACI&Oacute;N DE USUARIOS</font>\r\n");
      out.write("        <p>&nbsp;</p>\r\n");
      out.write("        </center>\r\n");
      out.write("        <center>\r\n");
      out.write("          <form action=\"gest_LoginPerf\" method=\"post\" name=\"theForm\">\r\n");
      out.write("          \t\t<input type=\"hidden\" name=\"accion\" value=\"inicio\" />\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"tipo_Login\" value=\"0\" />\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"autenti\" value=\"0\" />\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"redirect\" value=\"/MenuPrincipal.jsp\" />\r\n");
      out.write("            <table border=\"0\" width=\"90%\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"2\" align=\"center\"><p><font class=\"texto2\"><b>");
      out.print(mensaje);
      out.write("&nbsp;</b></font></p></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"2\" height=\"30\"><p>&nbsp;</p></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td align=\"right\" width=\"50%\"><b><font class=\"texto2\">Usuario:</font></b></td>\r\n");
      out.write("                    <td align=\"left\"  width=\"50%\"><input type=\"text\" class=\"inputText\" name=\"usuario\"></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td align=\"right\"><b><font class=\"texto2\">Contrase&ntilde;a:</font></b></td>\r\n");
      out.write("                    <td align=\"left\"><input type=\"password\" class=\"inputText\" name=\"password\" onKeyUp=\"detectarEnter(this)\"></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"2\" height=\"20\">&nbsp;</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"2\" height=\"20\" align=\"center\">\r\n");
      out.write("                      <A HREF=\"#\" onClick=\"Enviar()\">\r\n");
      out.write("                        <img src='images/Aceptar.jpg' name='aceptar' ALT='aceptar' border=\"0\">\r\n");
      out.write("                      </a>\r\n");
      out.write("                      </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("          </form>\r\n");
      out.write("          <script>document.theForm.usuario.focus()</script>\r\n");
      out.write("        </center>\r\n");
      out.write("      </td>\r\n");
      out.write("      <td width=\"10\" class=\"Fondoverdederecha\">\r\n");
      out.write("       &nbsp;\r\n");
      out.write("      </td>\r\n");
      out.write("    </TR>\r\n");
      out.write("    </TBODY>\r\n");
      out.write("  </TABLE>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "pie.jsp", out, true);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");


    } catch (Throwable t) {
        System.out.println(t);
    } finally{

    }

      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
