/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.4
 * Generated at: 2018-06-08 09:54:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import es.portanode.util.ProcesosBean;
import java.util.Vector;
import es.portanode.ficheros.Excell;
import es.portanode.util.html.SesionConectada;
import es.portanode.util.operadores.OperadorBean;
import java.util.Vector;
import java.util.Enumeration;
import es.gateway.sesiones.obj.Grupo;
import es.portanode.util.Singleton;
import es.portanode.util.operadores.OperadorMultipleBeanCollection;
import es.portanode.util.operadores.OperadorMultipleBean;
import es.portanode.util.html.SesionConectada;

public final class ConsultaHisProceso_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("jar:file:/C:/Users/x45558re/Desktop/entorno/tomcat-9.0/tomcat-9.0.4/wtpwebapps/GatewayRamaEstable/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098703890000L));
    _jspx_dependants.put("/cabeceraLogo.jsp", Long.valueOf(1528450505192L));
    _jspx_dependants.put("/WEB-INF/tld/struts-bean.tld", Long.valueOf(1528450506029L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1528450505299L));
    _jspx_dependants.put("/menu.jsp", Long.valueOf(1528450525562L));
    _jspx_dependants.put("/WEB-INF/tld/fmt.tld", Long.valueOf(1528450506098L));
    _jspx_dependants.put("/WEB-INF/tld/struts-logic.tld", Long.valueOf(1528450505979L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("es.portanode.util.ProcesosBean");
    _jspx_imports_classes.add("es.portanode.util.html.SesionConectada");
    _jspx_imports_classes.add("java.util.Vector");
    _jspx_imports_classes.add("java.util.Enumeration");
    _jspx_imports_classes.add("es.portanode.util.operadores.OperadorMultipleBeanCollection");
    _jspx_imports_classes.add("es.portanode.ficheros.Excell");
    _jspx_imports_classes.add("es.gateway.sesiones.obj.Grupo");
    _jspx_imports_classes.add("es.portanode.util.Singleton");
    _jspx_imports_classes.add("es.portanode.util.operadores.OperadorBean");
    _jspx_imports_classes.add("es.portanode.util.operadores.OperadorMultipleBean");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fbean_005fdefine_0026_005ftype_005fscope_005fname_005fid_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flogic_005fiterate_0026_005ftype_005fname_005findexId_005fid;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fmessage;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fbean_005fdefine_0026_005ftype_005fscope_005fname_005fid_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flogic_005fiterate_0026_005ftype_005fname_005findexId_005fid = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fmessage = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fbean_005fdefine_0026_005ftype_005fscope_005fname_005fid_005fnobody.release();
    _005fjspx_005ftagPool_005flogic_005fiterate_0026_005ftype_005fname_005findexId_005fid.release();
    _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname.release();
    _005fjspx_005ftagPool_005ffmt_005fmessage.release();
    _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.release();
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	try {

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Operador</title>\r\n");
      out.write("<META HTTP-EQUIV=\"expires\" CONTENT=\"1\">\r\n");
      out.write("<script language=\"JavaScript\" src=\"js/util.js\"></script>\r\n");
      out.write("<script language=\"JavaScript\" src=\"js/calendar1.js\"></script>\r\n");
      out.write("<link href=\"estilos/estilos.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String subtitulo1 = "Consulta Histórico Procesos";
		String contiene = (String) request.getAttribute("contiene");
		String rol = (String) request.getAttribute("Rol") == null ? "T"
				: (String) request.getAttribute("Rol");
		String ordenar = (String) request.getAttribute("Ordenar") == null ? "IDA"
				: (String) request.getAttribute("Ordenar");
		String limite = (String) request.getAttribute("Limite") == null ? "10"
				: (String) request.getAttribute("Limite");
		String tipoConsulta = ("-1".equals((String) request
				.getAttribute("TipoConsulta"))) ? "1"
				: (String) request.getAttribute("TipoConsulta");
		String buscaProceso = ("-1".equals((String) request
				.getAttribute("BuscaProceso"))) ? "1"
				: (String) request.getAttribute("BuscaProceso");
		String id_proceso = (String) request
				.getAttribute("Identificador") == null ? ""
				: (String) request.getAttribute("Identificador");
		String fechaInicial = (String) request
				.getAttribute("FechaInicial") == null ? ""
				: (String) request.getAttribute("FechaInicial");
		String fechaFinal = (String) request.getAttribute("FechaFinal") == null ? ""
				: (String) request.getAttribute("FechaFinal");
		String numInicial = (String) request.getAttribute("NumInicial") == null ? ""
				: (String) request.getAttribute("NumInicial");
		String numFinal = (String) request.getAttribute("NumFinal") == null ? ""
				: (String) request.getAttribute("NumFinal");
		String codigoOp = (String) request
				.getAttribute("CodigoOperador") == null ? ""
				: (String) request.getAttribute("CodigoOperador");
		String rolOp = ("".equals((String) request
				.getAttribute("RolOperador"))) ? "D" : (String) request
				.getAttribute("RolOperador");
		String rolNIF = ("".equals((String) request
				.getAttribute("RolNIF"))) ? "D" : (String) request
				.getAttribute("RolNIF");
		String fechaInicialOp = (String) request
				.getAttribute("FechaInicialOp") == null ? ""
				: (String) request.getAttribute("FechaInicialOp");
		String fechaFinalOp = (String) request
				.getAttribute("FechaFinalOp") == null ? ""
				: (String) request.getAttribute("FechaFinalOp");
		String NIF = (String) request.getAttribute("NIF") == null ? ""
				: (String) request.getAttribute("NIF");
		String total = (String) request.getAttribute("Total") == null ? "0"
				: (String) request.getAttribute("Total");
		String pagina = (String) request.getAttribute("Posicion");
		Vector vProcesos = (Vector) request
				.getAttribute("ListaProcesos");
		Vector vOperadores = (Vector) request
				.getAttribute("ListaOperadores");
		Vector vectorProcesos = (Vector) request
				.getAttribute("vectorProcesos");
		System.out.println("buscaProceso en jsp-------->"
				+ buscaProceso);
		String cadenaProcesos = "";
		String cadenaTotalProcesos = "";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<SCRIPT LANGUAGE=\"JavaScript\">\r\n");
      out.write("\r\n");
      out.write("function compruebaPatronNumero(f) {\r\n");
      out.write("    var numPat = /^[0-9]+%$/;\r\n");
      out.write("    var text = f.NumInicial.value;\r\n");
      out.write("    var result = text.match(numPat);\r\n");
      out.write("    if (result == null)\r\n");
      out.write("    {\r\n");
      out.write("        f.contiene.value = \"no\";\r\n");
      out.write("        return \"false\";\r\n");
      out.write("    } else {\r\n");
      out.write("        f.contiene.value = \"si\";\r\n");
      out.write("        return \"true\";\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function VerExcel() {\r\n");
      out.write("\r\n");
      out.write("    var f = document.formExcel;\r\n");
      out.write("    var f1 = document.formRadios;\r\n");
      out.write("    if (f1.tipoExcelF1[0].checked){\r\n");
      out.write("    \t f.tipoExcel.value = 'total';\r\n");
      out.write("    }else{\r\n");
      out.write("    \tf.tipoExcel.value = 'actual';\r\n");
      out.write("     }\r\n");
      out.write("    f.submit();\r\n");
      out.write("    info('El fichero excel se está generando, por favor espere', 'Proceso en curso');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function ajustarTamanioIFrame(idProceso, nMensajes) {\r\n");
      out.write("\r\n");
      out.write("    if (idProceso != null && nMensajes != 0) {\r\n");
      out.write("        var celda = document.getElementById(idProceso + \"P\");\r\n");
      out.write("        celda.height = 41 * nMensajes;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function Navegar(nPagina) {\r\n");
      out.write("    f = document.theForm;\r\n");
      out.write("    f.Posicion.value = nPagina;\r\n");
      out.write("    f.action = \"PrevioConsultaHisProceso\";\r\n");
      out.write("    f.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function Buscar() {\r\n");
      out.write("    f = document.theForm;\r\n");
      out.write("    var contiene = compruebaPatronNumero(f);\r\n");
      out.write("    f.action = \"PrevioConsultaHisProceso\";\r\n");
      out.write("    f.Total.value = \"0\";\r\n");
      out.write("    f.Posicion.value = \"1\";\r\n");
      out.write("    if (tipoConsulta == \"2\") {\r\n");
      out.write("        if (f.NumInicial.value == \"\") {\r\n");
      out.write("            alert(\"Debe introducir datos en el campo Rango Inicial\");\r\n");
      out.write("            f.NumInicial.focus();\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        if ((f.NumFinal.value == \"\") && (contiene == \"false\")) {\r\n");
      out.write("            f.NumFinal.value = f.NumInicial.value;\r\n");
      out.write("        }\r\n");
      out.write("        if ((f.NumFinal.value != \"\") && (contiene == \"true\")) {\r\n");
      out.write("            f.NumFinal.value = \"\";\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    if (tipoConsulta == \"3\") {\r\n");
      out.write("        if ((f.FechaInicialOp.value == \"\") || (f.FechaFinalOp.value == \"\")) {\r\n");
      out.write("            alert(\"Debe introducir un rango de fechas\");\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    if (tipoConsulta == \"4\") {\r\n");
      out.write("        if (f.NIF.value == \"\") {\r\n");
      out.write("            alert(\"Debe introducir un NIF/CIF\");\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    f.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function TodoOk(num) {\r\n");
      out.write("    var f = dameFormulario(num);\r\n");
      out.write("    var opciones = 'toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=yes,width=192,height=215,focus=true,Titlebar=no';\r\n");
      out.write("    var x = window.open('blanco.jsp', 'detalle', opciones);\r\n");
      out.write("    x.focus();\r\n");
      out.write("    x.resizeTo(500, 490);\r\n");
      out.write("    f.target = 'detalle';\r\n");
      out.write("    f.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var tipoConsulta = \"");
      out.print(tipoConsulta);
      out.write("\";\r\n");
      out.write("function CambiarConsulta(obj) {\r\n");
      out.write("    if (tipoConsulta != obj.value) {\r\n");
      out.write("        if (obj.value == 1) {\r\n");
      out.write("            show('TablaProceso');\r\n");
      out.write("            hide('TablaNumeracion');\r\n");
      out.write("            hide('TablaOperador');\r\n");
      out.write("            hide('TablaNIF');\r\n");
      out.write("            show('ComboRol');\r\n");
      out.write("            tipoConsulta = obj.value;\r\n");
      out.write("        }\r\n");
      out.write("        if (obj.value == 2) {\r\n");
      out.write("            hide('TablaProceso');\r\n");
      out.write("            show('TablaNumeracion');\r\n");
      out.write("            hide('TablaOperador');\r\n");
      out.write("            hide('TablaNIF');\r\n");
      out.write("            show('ComboRol');\r\n");
      out.write("            tipoConsulta = obj.value;\r\n");
      out.write("        }\r\n");
      out.write("        if (obj.value == 3) {\r\n");
      out.write("            hide('TablaProceso');\r\n");
      out.write("            hide('TablaNumeracion');\r\n");
      out.write("            show('TablaOperador');\r\n");
      out.write("            hide('TablaNIF');\r\n");
      out.write("            hide('ComboRol');\r\n");
      out.write("            tipoConsulta = obj.value;\r\n");
      out.write("        }\r\n");
      out.write("        if (obj.value == 4) {\r\n");
      out.write("            hide('TablaProceso');\r\n");
      out.write("            hide('TablaNumeracion');\r\n");
      out.write("            hide('TablaOperador');\r\n");
      out.write("            show('TablaNIF');\r\n");
      out.write("            hide('ComboRol');\r\n");
      out.write("            tipoConsulta = obj.value;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var bproceso = \"");
      out.print(buscaProceso);
      out.write("\";\r\n");
      out.write("function CambiaBusquedaProceso(obj) {\r\n");
      out.write("\r\n");
      out.write("    f = document.theForm;\r\n");
      out.write("    if (obj.value != bproceso) {\r\n");
      out.write("        bproceso = obj.value;\r\n");
      out.write("        if (bproceso == \"1\") {\r\n");
      out.write("            f.Identificador.disabled = false;\r\n");
      out.write("        }\r\n");
      out.write("        else f.Identificador.disabled = true;\r\n");
      out.write("\r\n");
      out.write("        showhide('cal1');\r\n");
      out.write("        f.FechaInicial.value = \"\";\r\n");
      out.write("        f.FechaFinal.value = \"\";\r\n");
      out.write("        showhide('cal2');\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("mostrar = new Image();\r\n");
      out.write("mostrar.src = \"images/mostrar.gif\";\r\n");
      out.write("ocultar = new Image();\r\n");
      out.write("ocultar.src = \"images/ocultar.gif\";\r\n");
      out.write("\r\n");
      out.write("function mostrarOcultar(imagen, num, id)\r\n");
      out.write("{\r\n");
      out.write("    if (imagen.name == \"ocultar\") {\r\n");
      out.write("        imagen.src = mostrar.src;\r\n");
      out.write("        imagen.name = \"mostrar\";\r\n");
      out.write("    }\r\n");
      out.write("    else {\r\n");
      out.write("        imagen.src = ocultar.src;\r\n");
      out.write("        imagen.name = \"ocultar\";\r\n");
      out.write("    }\r\n");
      out.write("    mostrarAlt(imagen);\r\n");
      out.write("    showhide(id);\r\n");
      out.write("    dameFormulario(num).submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function mostrarAlt(imagen) {\r\n");
      out.write("    if (imagen.name == \"ocultar\")\r\n");
      out.write("        imagen.alt = \"Pulse para Ocultar...\";\r\n");
      out.write("\r\n");
      out.write("    else\r\n");
      out.write("        imagen.alt = \"Pulse para Mostrar...\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function ordenarDatos(tipo) {\r\n");
      out.write("\r\n");
      out.write("    f = document.theForm;\r\n");
      out.write("    f.Ordenar.value = tipo;\r\n");
      out.write("    f.action = \"PrevioConsultaHisProceso\";\r\n");
      out.write("    f.submit();\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function desplegarTodos(img) {\r\n");
      out.write("    var esconder = \"\";\r\n");
      out.write("    if (img.name == \"ocultarTodas\") {\r\n");
      out.write("        img.src = mostrar.src;\r\n");
      out.write("        img.name = \"mostrarTodas\";\r\n");
      out.write("        img.alt = \"Pulse para Mostrar...\";\r\n");
      out.write("        esconder = \"hide\";\r\n");
      out.write("    } else {\r\n");
      out.write("        img.src = ocultar.src;\r\n");
      out.write("        img.name = \"ocultarTodas\";\r\n");
      out.write("        img.alt = \"Pulse para Ocultar...\";\r\n");
      out.write("        esconder = \"show\";\r\n");
      out.write("    }\r\n");
      out.write("    for (i = 0; i < document.images.length; i++)\r\n");
      out.write("    {\r\n");
      out.write("        imagen = document.images[i];\r\n");
      out.write("        if ((imagen.name == \"ocultar\") || (imagen.name == \"mostrar\")) {\r\n");
      out.write("            if (img.name == \"mostrarTodas\") {\r\n");
      out.write("                imagen.src = mostrar.src;\r\n");
      out.write("                imagen.name = \"mostrar\";\r\n");
      out.write("            } else {\r\n");
      out.write("                imagen.src = ocultar.src;\r\n");
      out.write("                imagen.name = \"ocultar\";\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        mostrarAlt(imagen);\r\n");
      out.write("    }\r\n");
if (vProcesos != null) {
					for (int i = 0; i < vProcesos.size(); i++) {
						ProcesosBean pBs = (ProcesosBean) vProcesos.get(i);
						String id = pBs.getID_PROCESO() + "P";
      out.write("\r\n");
      out.write("    if (esconder == \"show\")\r\n");
      out.write("        show('");
      out.print(id);
      out.write("');\r\n");
      out.write("    else\r\n");
      out.write("        hide('");
      out.print(id);
      out.write("');\r\n");
      out.write("    dameFormulario('");
      out.print((i + 1));
      out.write("').submit();\r\n");
}
				}
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function generarExcel() {\r\n");
      out.write("    f = document.formExcel;\r\n");
      out.write("    f.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<body leftMargin=0 topMargin=0 marginheight=\"0\" marginwidth=\"0\">\r\n");
      out.write("\r\n");
      out.write("<!-- Insercion de Cabecera -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/ComprobarSesion", out, false);
      out.write("\r\n");
      out.write("  ");


      SesionConectada cs2 = new SesionConectada(request);
      String operadorSesion = cs2.GetOperador();
      System.out.println("cabeceraLogo: oper sera "+cs2.GetOperador());

      String imagen = operadorSesion;
      if(imagen==null)
      {
        imagen = (String) request.getAttribute("OperadorConexion");
      }
      if(imagen==null)
      {
         imagen = (String) request.getAttribute("OperadorConectado");
      }
      if(imagen==null)
      {
          imagen="";
      }

      /*
        String imagen = (String) request.getAttribute("OperadorConexion");
        if(imagen==null) imagen = (String) request.getAttribute("OperadorConectado");
        if(imagen==null)  imagen="";
        */
    String logo = "";
    if ((imagen==null)||(imagen.equals(""))){
       logo = "<img src='images/telefono.jpg' name='logotipo' width='90' height='56'>";
    }
    else{
       logo = "<img src='images/"+imagen+".gif' name='logotipo' ALT='Operador' height='56'>";
    }
    boolean isAdmin = false;
    String esAdmin=(String)request.getAttribute("isAdmin");
    if ("true".equals(esAdmin)){
      isAdmin = true;
    }
    String nombreServlet = getServletConfig().getServletName();


      String usuarioCabecera = cs2.GetSuserId();
      System.out.println(usuarioCabecera);
      OperadorMultipleBeanCollection mOperadoresCabecera = new OperadorMultipleBeanCollection (null,usuarioCabecera );
      Vector vOperadoresCabecera = mOperadoresCabecera.getMultiOperador ( );
      int totalOperadoresCabecera = vOperadoresCabecera.size();

      Vector vGrupos = (Vector)session.getAttribute("grupos");
      String grupoActivo = (String)session.getAttribute("grupoActivo");      

  
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/ventana-modal-1.3.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/abrir-ventana-alertas.js\"></script>\r\n");
      out.write("<link href=\"estilos/ventana-modal.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("    //Función que permite abrir el fichero de ayuda correspondiente a la página.\r\n");
      out.write("    function ayuda()\r\n");
      out.write("    {\r\n");
      out.write("        var p = '");
      out.print(nombreServlet);
      out.write("';\r\n");
      out.write("        window.open('ayuda/' + p + '.htm', 'AYUDA', 'toolbar=no,location=no,directories=no,status=no,menubar=no,resizable=yes,scrollbars=yes,width=750');\r\n");
      out.write("    }\r\n");
      out.write("    function CambioOper()\r\n");
      out.write("    {\r\n");
      out.write("        f = document.formularioCabecera;\r\n");
      out.write("        f.action = \"CambioOperadorSesion\";\r\n");
      out.write("        f.submit();\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function CambioGrupo(){\r\n");
      out.write("        f = document.formularioCabecera;\r\n");
      out.write("        f.action = \"CambioGrupoSesion\";\r\n");
      out.write("        f.submit();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<!-- Fin Insercion de Cabecera -->\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" height=\"56\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"40%\" class='celdalineaabajo'>");
      out.print(logo);
      out.write("</td>\r\n");
      out.write("    <td width=\"20%\" class='celdalineaabajo' colspan=\"2\" align=\"center\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr><td align=\"center\"><img src='images/portanode.png' name='logotipo' ALT='Operador'></td></tr>\r\n");
      out.write("           \t<tr><td>&nbsp;</td></tr>\r\n");
      out.write("        </table>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td width=\"40%\" align=\"right\" class='celdalineaabajo' valign=\"center\">\r\n");
      out.write("      <table border=\"0\">\r\n");
      out.write("       <tr>\r\n");
      out.write("         <td align=\"right\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<font class=\"texto3\">subtitulo1</font>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("         </td>\r\n");
      out.write("       </tr>\r\n");
      out.write("       <tr>\r\n");
      out.write("         <td align=\"right\">\r\n");
      out.write("           <a  href=\"javascript:ayuda()\"><img src=\"images/help.gif\" alt=\"Manual de usuario\" border=\"0\"></a>\r\n");
      out.write("         </td>\r\n");
      out.write("       </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>");
      out.write("\r\n");
      out.write("<table width='100%' height='90%' border='0' cellpadding='0'\r\n");
      out.write("\tcellspacing='0'>\r\n");
      out.write("\t<TBODY>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<td width=\"10\" class=\"Fondoverdederecha\">&nbsp;</td>\r\n");
      out.write("\t\t\t<TD vAlign=top width=\"180\" class=\"celdalineaderecha\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String fechaSistema = (String) request.getAttribute("FechaSistema");
 System.out.println(fechaSistema);
 

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("\t\t//Función que permite abrir el fichero de ayuda correspondiente a la página\r\n");
      out.write("\r\n");
      out.write("\t\tfunction lanzaFormularioDe3(accionName, metodo, numForm){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(accionName==\"MenuOpcionesUsuario\"){\r\n");
      out.write("\t\t\t\tf = document.MenuOpcionesUsuario;\r\n");
      out.write("\t\t\t\tf.accion.value = metodo;\r\n");
      out.write("\t\t\t}else if(accionName==\"ConsultaExpirados\"){\r\n");
      out.write("\t\t\t\tf = document.Generico;\r\n");
      out.write("\t\t\t\tf.Accion.value = metodo;\r\n");
      out.write("                f.action = accionName;\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tf = document.Generico;\r\n");
      out.write("\t\t\t\tf.action = accionName;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tf.submit();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction lanzaFormularioDe2(accionName){\r\n");
      out.write("\t\t\tf = document.Generico;\r\n");
      out.write("\t\t\tf.action = accionName;\r\n");
      out.write("\t\t\tf.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction lanzaSalir(formName, accionName){\r\n");
      out.write("\t\t\tf = document.forms[formName];\r\n");
      out.write("\t\t\tf.accion.value = accionName;\r\n");
      out.write("\t\t\tf.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction lanzaModuloUsuarios(accionName){\r\n");
      out.write("\t\t\tf = document.MenuOpcionesUsuario;\r\n");
      out.write("\t\t\tf.accion.value = accionName;\r\n");
      out.write("\t\t\tf.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      //  bean:define
      org.apache.struts.taglib.bean.DefineTag _jspx_th_bean_005fdefine_005f0 = (org.apache.struts.taglib.bean.DefineTag) _005fjspx_005ftagPool_005fbean_005fdefine_0026_005ftype_005fscope_005fname_005fid_005fnobody.get(org.apache.struts.taglib.bean.DefineTag.class);
      boolean _jspx_th_bean_005fdefine_005f0_reused = false;
      try {
        _jspx_th_bean_005fdefine_005f0.setPageContext(_jspx_page_context);
        _jspx_th_bean_005fdefine_005f0.setParent(null);
        // /menu.jsp(52,0) name = id type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_bean_005fdefine_005f0.setId("permisosLink");
        // /menu.jsp(52,0) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_bean_005fdefine_005f0.setType("java.util.ArrayList");
        // /menu.jsp(52,0) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_bean_005fdefine_005f0.setName("links");
        // /menu.jsp(52,0) name = scope type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_bean_005fdefine_005f0.setScope("session");
        int _jspx_eval_bean_005fdefine_005f0 = _jspx_th_bean_005fdefine_005f0.doStartTag();
        if (_jspx_th_bean_005fdefine_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fbean_005fdefine_0026_005ftype_005fscope_005fname_005fid_005fnobody.reuse(_jspx_th_bean_005fdefine_005f0);
        _jspx_th_bean_005fdefine_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_bean_005fdefine_005f0, _jsp_getInstanceManager(), _jspx_th_bean_005fdefine_005f0_reused);
      }
      java.util.ArrayList permisosLink = null;
      permisosLink = (java.util.ArrayList) _jspx_page_context.findAttribute("permisosLink");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table cellSpacing=0 cellPadding=0 border=0 width=\"100%\">\r\n");
      out.write("    <FORM METHOD=POST ACTION=\"MenuPrincipal\" name=\"Generico\">\r\n");
      out.write("       <INPUT TYPE=\"hidden\" name=\"OperadorConexion\" value=\"");
      out.print(imagen);
      out.write("\">\r\n");
      out.write("       <INPUT TYPE=\"hidden\" name=\"OperadorConectado\" value=\"");
      out.print(imagen);
      out.write("\">\r\n");
      out.write("       <INPUT TYPE=\"hidden\" NAME=\"Posicion\" VALUE=\"1\">\r\n");
      out.write("       <INPUT TYPE=\"hidden\" NAME=\"Fecha\" VALUE=\"");
      out.print(fechaSistema);
      out.write("\">\r\n");
      out.write("       <INPUT TYPE=\"hidden\" NAME=\"Accion\" VALUE=\"\">\r\n");
      out.write("    </form>\r\n");
      out.write("    <form method=post action=\"MenuOpcionesUsuario.do\" name=\"MenuOpcionesUsuario\"> \r\n");
      out.write("    <input type=\"hidden\" name=\"accion\" value=\"\">\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      //  logic:iterate
      org.apache.struts.taglib.logic.IterateTag _jspx_th_logic_005fiterate_005f0 = (org.apache.struts.taglib.logic.IterateTag) _005fjspx_005ftagPool_005flogic_005fiterate_0026_005ftype_005fname_005findexId_005fid.get(org.apache.struts.taglib.logic.IterateTag.class);
      boolean _jspx_th_logic_005fiterate_005f0_reused = false;
      try {
        _jspx_th_logic_005fiterate_005f0.setPageContext(_jspx_page_context);
        _jspx_th_logic_005fiterate_005f0.setParent(null);
        // /menu.jsp(66,0) name = id type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_logic_005fiterate_005f0.setId("link");
        // /menu.jsp(66,0) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_logic_005fiterate_005f0.setName("permisosLink");
        // /menu.jsp(66,0) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_logic_005fiterate_005f0.setType("es.gateway.sesiones.permisos.bean.LinkBean");
        // /menu.jsp(66,0) name = indexId type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_logic_005fiterate_005f0.setIndexId("ij");
        int _jspx_eval_logic_005fiterate_005f0 = _jspx_th_logic_005fiterate_005f0.doStartTag();
        if (_jspx_eval_logic_005fiterate_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          es.gateway.sesiones.permisos.bean.LinkBean link = null;
          java.lang.Integer ij = null;
          if (_jspx_eval_logic_005fiterate_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_logic_005fiterate_005f0);
          }
          link = (es.gateway.sesiones.permisos.bean.LinkBean) _jspx_page_context.findAttribute("link");
          ij = (java.lang.Integer) _jspx_page_context.findAttribute("ij");
          do {
            out.write('\r');
            out.write('\n');
            out.write('	');
            if (_jspx_meth_logic_005fempty_005f0(_jspx_th_logic_005fiterate_005f0, _jspx_page_context))
              return;
            out.write('\r');
            out.write('\n');
            out.write('	');
            //  logic:notEmpty
            org.apache.struts.taglib.logic.NotEmptyTag _jspx_th_logic_005fnotEmpty_005f0 = (org.apache.struts.taglib.logic.NotEmptyTag) _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.get(org.apache.struts.taglib.logic.NotEmptyTag.class);
            boolean _jspx_th_logic_005fnotEmpty_005f0_reused = false;
            try {
              _jspx_th_logic_005fnotEmpty_005f0.setPageContext(_jspx_page_context);
              _jspx_th_logic_005fnotEmpty_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fiterate_005f0);
              // /menu.jsp(80,1) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_logic_005fnotEmpty_005f0.setName("link");
              // /menu.jsp(80,1) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_logic_005fnotEmpty_005f0.setProperty("idPadre");
              int _jspx_eval_logic_005fnotEmpty_005f0 = _jspx_th_logic_005fnotEmpty_005f0.doStartTag();
              if (_jspx_eval_logic_005fnotEmpty_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("\t\t<TR onMouseOver=\"this.className='Fondoverdeover'\" onMouseOut=\"this.className='Fondoblanco'\">\r\n");
                  out.write("\r\n");
                  out.write("\r\n");
                  out.write("\t\t\t\t<input type=\"hidden\" name=\"accion\" value=\"\">\r\n");
                  out.write("\r\n");
                  out.write("\t\t\t\t<TD valign=\"top\">&nbsp;</TD>\r\n");
                  out.write("\t\t\t\t<TD width=6 valign=\"top\">&nbsp;</TD>\r\n");
                  out.write("\t\t\t\t<TD width=172 colspan=\"2\">\r\n");
                  out.write("\t\t\t\t");
for (int i=0;i<link.getNivel().intValue()-2;i++){ out.print("&nbsp");}
                  out.write("\r\n");
                  out.write("\t\t\t\t\t<IMG height=9 src=\"images/cuadro.gif\" width=9 alt=\"->\"> \r\n");
                  out.write("\t\t\t\t\t\r\n");
                  out.write("\t\t\t\t\t<a href=\"#\" onclick=\"javascript:lanzaFormularioDe3('");
                  if (_jspx_meth_bean_005fwrite_005f1(_jspx_th_logic_005fnotEmpty_005f0, _jspx_page_context))
                    return;
                  out.write("', '");
                  if (_jspx_meth_bean_005fwrite_005f2(_jspx_th_logic_005fnotEmpty_005f0, _jspx_page_context))
                    return;
                  out.write("', '");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ij}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("')\" \r\n");
                  out.write("\t\t\t\t\t\tonMouseOver=\"window.status='");
                  if (_jspx_meth_fmt_005fmessage_005f1(_jspx_th_logic_005fnotEmpty_005f0, _jspx_page_context))
                    return;
                  out.write("';return true\"\r\n");
                  out.write("\t\t\t\t\t\tonMouseOut=\"window.status=' '\" class=\"itemmenu\">\r\n");
                  out.write("\t\t\t\t\t\t");
                  if (_jspx_meth_fmt_005fmessage_005f2(_jspx_th_logic_005fnotEmpty_005f0, _jspx_page_context))
                    return;
                  out.write("\r\n");
                  out.write("\t\t\t\t\t</a>\r\n");
                  out.write("\t\t\t\t</TD>\r\n");
                  out.write("\t\t</TR>\r\n");
                  out.write("\t");
                  int evalDoAfterBody = _jspx_th_logic_005fnotEmpty_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_logic_005fnotEmpty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.reuse(_jspx_th_logic_005fnotEmpty_005f0);
              _jspx_th_logic_005fnotEmpty_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fnotEmpty_005f0, _jsp_getInstanceManager(), _jspx_th_logic_005fnotEmpty_005f0_reused);
            }
            out.write('\r');
            out.write('\n');
            int evalDoAfterBody = _jspx_th_logic_005fiterate_005f0.doAfterBody();
            link = (es.gateway.sesiones.permisos.bean.LinkBean) _jspx_page_context.findAttribute("link");
            ij = (java.lang.Integer) _jspx_page_context.findAttribute("ij");
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_logic_005fiterate_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
          }
        }
        if (_jspx_th_logic_005fiterate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005flogic_005fiterate_0026_005ftype_005fname_005findexId_005fid.reuse(_jspx_th_logic_005fiterate_005f0);
        _jspx_th_logic_005fiterate_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fiterate_005f0, _jsp_getInstanceManager(), _jspx_th_logic_005fiterate_005f0_reused);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<TR>\r\n");
      out.write("\t\t<TD valign=\"top\">&nbsp;</TD>\r\n");
      out.write("\t\t<TD colSpan=3 valign=\"top\" class=\"itemmenubold\">\r\n");
      out.write("\t\t\t<br>&nbsp;</BR>\r\n");
      out.write("\t\t</TD>\r\n");
      out.write("\t</TR>\r\n");
      out.write("\r\n");
      out.write("    <TR onMouseOver=\"this.className='Fondoverdeover'\" onMouseOut=\"this.className='Fondoblanco'\">\r\n");
      out.write("\t\t <form method=post action=\"MenuSalir.do\" name=\"MenuSalirForm\"> \r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"accion\" value=\"salir\"> \r\n");
      out.write("\t\t\t<TD valign=\"top\">&nbsp;</TD>\r\n");
      out.write("\t\t\t<TD width=6 valign=\"top\">&nbsp;</TD>\r\n");
      out.write("\t\t\t<TD width=12>\r\n");
      out.write("\t\t\t\t<IMG height=9 src=\"images/cuadro.gif\" width=9 alt=\"->\">\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t        <TD width=160>\r\n");
      out.write("\t\t\t\t<A href=\"#\" onclick=\"javascript:lanzaSalir('MenuSalirForm', 'salir')\"\r\n");
      out.write("\t\t\t\t\tonMouseOver=\"window.status='");
      if (_jspx_meth_fmt_005fmessage_005f3(_jspx_page_context))
        return;
      out.write("';return true\"\r\n");
      out.write("\t\t\t\t\tonMouseOut=\"window.status=' '\" class=\"itemmenu\">\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_fmt_005fmessage_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t </FORM> \r\n");
      out.write("\t</TR>\r\n");
      out.write("\r\n");
      out.write("</table>");
      out.write("</TD>\r\n");
      out.write("\t\t\t<!-- InstanceBeginEditable name=\"contenido\" -->\r\n");
      out.write("\t\t\t<TD class=Titulo vAlign=top align=middle\r\n");
      out.write("\t\t\t\tbackground=\"images/fondocentro.gif\"><br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<DIV align=left class=\"Titulo\">&nbsp;&nbsp;&nbsp;<img\r\n");
      out.write("\t\t\t\tsrc=\"images/flecha.gif\" border=\"0\" />Consulta Hist&oacute;rico\r\n");
      out.write("\t\t\tProcesos</DIV>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<form action=\"\" method=\"post\" name=\"theForm\" class=\"texto2\"><input\r\n");
      out.write("\t\t\t\ttype=\"hidden\" name=\"Ordenar\" value=\"");
      out.print(ordenar);
      out.write("\"> <input\r\n");
      out.write("\t\t\t\ttype=\"hidden\" name=\"Total\" value=\"");
      out.print(total);
      out.write("\"> <input\r\n");
      out.write("\t\t\t\ttype=\"hidden\" name=\"Posicion\" value=\"");
      out.print(pagina);
      out.write("\"> <input\r\n");
      out.write("\t\t\t\ttype=\"hidden\" name=\"contiene\" value=\"");
      out.print(contiene);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table width=\"90%\" border=\"0\" align=\"center\" cellspacing=\"4\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"20%\" valign=\"top\">\r\n");
      out.write("\t\t\t\t\t<table width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><label> <input type=\"radio\" name=\"TipoConsulta\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"1\" ");
if (tipoConsulta.equals("1")) {
      out.write(" checked ");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tonClick=\"CambiarConsulta(this)\"> <font class=\"texto2\">Por\r\n");
      out.write("\t\t\t\t\t\t\tProceso</font></label></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><label> <input type=\"radio\" name=\"TipoConsulta\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"2\" ");
if (tipoConsulta.equals("2")) {
      out.write(" checked ");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tonClick=\"CambiarConsulta(this)\"> <font class=\"texto2\">Por\r\n");
      out.write("\t\t\t\t\t\t\tNumeración</font></label></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><label> <input type=\"radio\" name=\"TipoConsulta\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"3\" ");
if (tipoConsulta.equals("3")) {
      out.write(" checked ");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tonClick=\"CambiarConsulta(this)\"> <font class=\"texto2\">Por\r\n");
      out.write("\t\t\t\t\t\t\tOperador</font></label></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><label> <input type=\"radio\" name=\"TipoConsulta\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"4\" ");
if (tipoConsulta.equals("4")) {
      out.write(" checked ");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tonClick=\"CambiarConsulta(this)\"> <font class=\"texto2\">Por\r\n");
      out.write("\t\t\t\t\t\t\tNIF/CIF</font></label></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td height=\"1\" background=\"images/separador.gif\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"texto2\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t<table id='ComboRol'\r\n");
      out.write("\t\t\t\t\t\t\t\t");
if (tipoConsulta.equals("3") || tipoConsulta.equals("4")) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"display: none\" ");
}
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><label><font class=\"texto2\">Rol:\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;</font></label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><select name=\"Rol\" class=\"pie\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"D\" ");
if (rol.equals("D")) {
      out.write(" selected ");
}
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tDonante</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"R\" ");
if (rol.equals("R")) {
      out.write(" selected ");
}
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tReceptor</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"O\" ");
if (rol.equals("O")) {
      out.write(" selected ");
}
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tOtro</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"T\" ");
if (rol.equals("T")) {
      out.write(" selected ");
}
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tTodos</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"texto2\" height=\"30\">L&iacute;mite: &nbsp;&nbsp; <select\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"Limite\" class=\"pie\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"10\" ");
if (limite.equals("10")) {
      out.write(" selected ");
}
      out.write(">10</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"20\" ");
if (limite.equals("20")) {
      out.write(" selected ");
}
      out.write(">20</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"30\" ");
if (limite.equals("30")) {
      out.write(" selected ");
}
      out.write(">30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"40\" ");
if (limite.equals("40")) {
      out.write(" selected ");
}
      out.write(">40</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"50\" ");
if (limite.equals("50")) {
      out.write(" selected ");
}
      out.write(">50</option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td valign=\"top\">\r\n");
      out.write("\t\t\t\t\t<table width=\"100%\" border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"right\" colspan=\"5\"><A HREF=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonClick=\"Navegar(");
      out.print(pagina);
      out.write(");\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonMouseOver=\"window.status='Recargar';return true;\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonMouseOut=\"window.status=' '\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"images/recargar.gif\" border=\"0\" alt=\"Recargar\"></A></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<table width=\"100%\" border=\"0\" id=\"TablaProceso\"\r\n");
      out.write("\t\t\t\t\t\t\t\t");
if (!tipoConsulta.equals("1")) {
      out.write(" style=\"display: none\" ");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tcellpadding=\"4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td colspan=\"5\" class=\"cabeceratabla\" height=\"20\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tProcesos&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"7%\"><input type=\"radio\" name=\"BuscaProceso\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"1\" ");
if (buscaProceso.equals("1")) {
      out.write(" checked ");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonClick=\"CambiaBusquedaProceso(this)\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"21%\"><font class=\"texto2\">Identificador\r\n");
      out.write("\t\t\t\t\t\t\t\t\t:</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"26%\"><input name=\"Identificador\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(id_proceso);
      out.write("\" type=\"text\" class=\"inputText\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsize=\"22\" maxlength=\"20\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"17%\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"29%\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"7%\"><input type=\"radio\" name=\"BuscaProceso\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
if (buscaProceso.equals("2")) {
      out.write(" checked ");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonClick=\"CambiaBusquedaProceso(this)\" value=\"2\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><font class=\"texto2\">Fecha Inicial :</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input name=\"FechaInicial\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"inputText\" value=\"");
      out.print(fechaInicial);
      out.write("\" size=\"15\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\treadonly=\"readonly\" maxlength=\"10\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"javascript:calendario1.popup();\"><img id=\"cal1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"images/calendar/cal.gif\" width=\"16\" height=\"16\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tborder=\"0\" alt=\"Calendario\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
if (buscaProceso.equals("1")) {
      out.write(" style=\"display: none\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
}
      out.write("></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><font class=\"texto2\">Fecha Final :</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input name=\"FechaFinal\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(fechaFinal);
      out.write("\" class=\"inputText\" size=\"15\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\treadonly=\"readonly\" maxlength=\"10\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"javascript:calendario2.popup();\"><img id=\"cal2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"images/calendar/cal.gif\" width=\"16\" height=\"16\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tborder=\"0\" alt=\"Calendario\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
if (buscaProceso.equals("1")) {
      out.write(" style=\"display: none\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
}
      out.write("></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td valign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t<table width=\"100%\" border=\"0\" id=\"TablaNumeracion\"\r\n");
      out.write("\t\t\t\t\t\t\t\t");
if (!tipoConsulta.equals("2")) {
      out.write(" style=\"display: none\" ");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tcellpadding=\"4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td colspan=\"4\" class=\"cabeceratabla\" height=\"20\">Numeraci&oacute;n&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"17%\"><font class=\"texto2\">Num Inicial :\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"30%\"><input type=\"text\" name=\"NumInicial\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(numInicial);
      out.write("\" class=\"inputText\" size=\"21\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmaxlength=\"15\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"14%\"><font class=\"texto2\">Num Final : </font></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"31%\"><input type=\"text\" name=\"NumFinal\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(numFinal);
      out.write("\" class=\"inputText\" size=\"21\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmaxlength=\"15\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<table width=\"100%\" border=\"0\" id=\"TablaOperador\"\r\n");
      out.write("\t\t\t\t\t\t\t\t");
if (!tipoConsulta.equals("3")) {
      out.write(" style=\"display: none\" ");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tcellpadding=\"4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td colspan=\"2\" class=\"cabeceratabla\" height=\"20\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tOperador&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td colspan=\"2\" class=\"texto2\" align=\"center\">Operador:&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"CodigoOperador\" class=\"pie\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											for (int i = 0; i < vOperadores.size(); i++) {
													OperadorBean operador = (OperadorBean) vOperadores.get(i);
													if (!operador.getCodigo().equals(operadorSesion)) {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print(operador.getCodigo());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
if (codigoOp.equals(operador.getCodigo())) {
      out.write(" selected\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
}
      out.write('>');
      out.print(operador.getDescripcion());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											}
												}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table width=\"100%\" border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\"><font class=\"texto2\">Fecha\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tInicial:&nbsp;</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\"><input name=\"FechaInicialOp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"inputText\" value=\"");
      out.print(fechaInicialOp);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tsize=\"15\" readonly=\"readonly\" maxlength=\"10\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\thref=\"javascript:calendario3.popup();\"><img id=\"cal3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"images/calendar/cal.gif\" width=\"16\" height=\"16\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tborder=\"0\" alt=\"Calendario\"></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\"><font class=\"texto2\">Fecha\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tFinal:&nbsp;</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\"><input name=\"FechaFinalOp\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(fechaFinalOp);
      out.write("\" class=\"inputText\" size=\"15\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\treadonly=\"readonly\" maxlength=\"10\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\thref=\"javascript:calendario4.popup();\"><img id=\"cal4\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"images/calendar/cal.gif\" width=\"16\" height=\"16\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tborder=\"0\" alt=\"Calendario\"></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table width=\"100%\" border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"texto2\"><input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tname=\"RolOperador\" value=\"D\" ");
if (rolOp.equals("D")) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tchecked ");
}
      out.write(">Rol Donante</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"texto2\"><input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tname=\"RolOperador\" value=\"R\" ");
if (rolOp.equals("R")) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tchecked ");
}
      out.write(">Rol Receptor</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<table width=\"100%\" border=\"0\" id=\"TablaNIF\"\r\n");
      out.write("\t\t\t\t\t\t\t\t");
if (!tipoConsulta.equals("4")) {
      out.write(" style=\"display: none\" ");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tcellpadding=\"4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td colspan=\"2\" class=\"cabeceratabla\" height=\"20\">NIF/CIF&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\"><font class=\"texto2\">NIF/CIF:&nbsp;</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input name=\"NIF\" type=\"text\" class=\"inputText\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(NIF);
      out.write("\" size=\"15\" maxlength=\"15\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table width=\"100%\" border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"texto2\"><input type=\"radio\" name=\"RolNIF\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"D\" ");
if (rolNIF.equals("D")) {
      out.write(" checked ");
}
      out.write(">Rol\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tDonante</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"texto2\"><input type=\"radio\" name=\"RolNIF\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"R\" ");
if (rolNIF.equals("R")) {
      out.write(" checked ");
}
      out.write(">Rol\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tReceptor</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"texto2\"><input type=\"radio\" name=\"RolNIF\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"T\" ");
if (rolNIF.equals("T")) {
      out.write(" checked ");
}
      out.write(">Ambos\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tRoles</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<center><A HREF=\"javascript:Buscar()\"\r\n");
      out.write("\t\t\t\tonMouseOver=\"window.status='Realizar búsqueda';return true;\"\r\n");
      out.write("\t\t\t\tonMouseOut=\"window.status=' '\"><img src=\"images/buscar.gif\"\r\n");
      out.write("\t\t\t\twidth=\"107\" height=\"28\" onClick=\"\" border=\"0\"></a></center>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

   			 if (vProcesos!=null && vProcesos.size() > 0) {
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<form name=\"formRadios\">\r\n");
      out.write(" <table>\r\n");
      out.write("    \t<tr align=\"center\">\r\n");
      out.write("    \t\t<td class=\"texto\"><input type=\"radio\" name=\"tipoExcelF1\"  value=\"total\"> Vista total</td>\r\n");
      out.write("    \t\t<td class=\"texto\"><input type=\"radio\" name=\"tipoExcelF1\" value=\"actual\" checked> Vista actual</td>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");


    }


      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<table width=\"98%\" border=\"1\" align=\"center\" class=\"tablas\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"bgCabeceraFila\"><img align=\"middle\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"javascript:desplegarTodos(this)\" name=\"mostrarTodas\"\r\n");
      out.write("\t\t\t\t\t\tborder=\"0\" height=\"13\" width=\"14\" src=\"images/mostrar.gif\" /> T</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"bgCabeceraFila\" align=\"center\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"images/ascen.gif\" border=\"0\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Ordenar por IdProceso Ascendente\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"ordenarDatos('IDA')\"> &nbsp; &nbsp; Id. proceso\r\n");
      out.write("\t\t\t\t\t&nbsp; &nbsp; <img src=\"images/descen.gif\" border=\"0\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Ordenar por IdProceso Descendente\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"ordenarDatos('IDD')\"></td>\r\n");
      out.write("\t\t\t\t\t<td class=\"bgCabeceraFila\" align=\"center\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"images/ascen.gif\" border=\"0\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Ordenar por Fecha Ascendente\" onclick=\"ordenarDatos('FA')\">\r\n");
      out.write("\t\t\t\t\t&nbsp; &nbsp; Fecha Inicio &nbsp; &nbsp; <img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"images/descen.gif\" border=\"0\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Ordenar por Fecha Descendente\" onclick=\"ordenarDatos('FD')\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"bgCabeceraFila\" align=\"center\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"images/ascen.gif\" border=\"0\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Ordenar por Estado Ascendente\" onclick=\"ordenarDatos('EA')\">\r\n");
      out.write("\t\t\t\t\t&nbsp; &nbsp; Estado &nbsp; &nbsp; <img src=\"images/descen.gif\"\r\n");
      out.write("\t\t\t\t\t\tborder=\"0\" alt=\"Ordenar por Estado Descendente\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"ordenarDatos('ED')\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<!-- Listamos todos los procesos -->\r\n");
      out.write("\t\t\t\t");

				
				 if(vectorProcesos!=null){
				    	for(int k=0;k<vectorProcesos.size();k++){
				        	ProcesosBean pbt = (ProcesosBean) vectorProcesos.get(k);
				        	cadenaTotalProcesos = cadenaTotalProcesos + pbt.getID_PROCESO() + "-" + pbt.getFECHA_INICIO() + "-" + pbt.getESTADO() + ((k == vectorProcesos.size() - 1) ? "" : "&");
				        }
				    }
				
					int j = 1;
						String clase = "";
						if (vProcesos != null) {
							for (int i = 0; i < vProcesos.size(); i++) {
								ProcesosBean pB = (ProcesosBean) vProcesos.get(i);
								cadenaProcesos = cadenaProcesos + pB.getID_PROCESO()
										+ "-" + pB.getFECHA_INICIO() + "-"
										+ pB.getESTADO()
										+ ((i == vProcesos.size() - 1) ? "" : "&");
								int indice = j;
								j++;
								if ((i % 2) == 0)
									clase = "";
								else
									clase = "bgFila";
				
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<form action=\"DetalleHisProceso\"\r\n");
      out.write("\t\t\t\t\t\ttarget=\"iframe");
      out.print((pB.getID_PROCESO()));
      out.write("\" method=post\r\n");
      out.write("\t\t\t\t\t\tname=\"form");
      out.print(indice);
      out.write("\"><INPUT TYPE=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\tname=\"idProceso\" value=\"");
      out.print(pB.getID_PROCESO());
      out.write("\"> <INPUT\r\n");
      out.write("\t\t\t\t\t\tTYPE=\"hidden\" name=\"OperadorConexion\" value=\"");
      out.print(imagen);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<td class=\"");
      out.print(clase);
      out.write("\" align=\"center\"><img align=\"middle\"\r\n");
      out.write("\t\t\t\t\t\tname=\"mostrar\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"mostrarOcultar(this,");
      out.print(indice);
      out.write(',');
      out.write('\'');
      out.print(pB.getID_PROCESO() + "P");
      out.write("');\"\r\n");
      out.write("\t\t\t\t\t\tborder=\"0\" height=\"13\" width=\"14\" src=\"images/mostrar.gif\"\r\n");
      out.write("\t\t\t\t\t\tonMouseOver=\"mostrarAlt(this)\" /></td>\r\n");
      out.write("\t\t\t\t\t<td class=\"");
      out.print(clase);
      out.write("\" align=\"center\"><font class=\"texto2\">");
      out.print(pB.getID_PROCESO());
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"");
      out.print(clase);
      out.write("\" align=\"center\"><font class=\"texto2\">");
      out.print(pB.getFECHA_INICIO());
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"");
      out.print(clase);
      out.write("\" align=\"center\"><font class=\"texto2\">");
      out.print(pB.getESTADO());
      out.write("</font></td>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr style=\"display: none\" height=\"10\"\r\n");
      out.write("\t\t\t\t\tid=\"");
      out.print(pB.getID_PROCESO() + "P");
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<td colspan='4'><iframe width=\"100%\" height=\"100%\"\r\n");
      out.write("\t\t\t\t\t\tid=\"iframe");
      out.print((pB.getID_PROCESO()));
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tname=\"iframe");
      out.print((pB.getID_PROCESO()));
      out.write("\" src=\"DetalleProcesoJSP\"\r\n");
      out.write("\t\t\t\t\t\tframeborder=\"0\" allowTransparency=\"true\"></iframe></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");

					}
						}
				
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/NavegadorJSP" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Limit", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(limite), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Total", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(total), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("ActualLink", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(pagina), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("DirectURL", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("javascript:Navegar(", request.getCharacterEncoding()), out, true);
      out.write(' ');
      out.write(' ');

    if (vProcesos!=null && vProcesos.size() > 0) {

      out.write("\r\n");
      out.write("    <form action=\"GenerarExcelTotal\" method=post name=\"formExcel\">\r\n");
      out.write("    <INPUT TYPE=\"hidden\" name=\"cadenaProcesos\" value=\"");
      out.print(cadenaProcesos);
      out.write("\">\r\n");
      out.write("    <input type=\"hidden\" name=\"cadenaTotalProcesos\" value=\"");
      out.print(cadenaTotalProcesos);
      out.write("\">\r\n");
      out.write("    <input type=\"hidden\" name=\"tipoExcel\">\r\n");
      out.write("    <table>\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<td><A HREF=\"javascript:VerExcel()\" onMouseOver=\"window.status='Consulta Offline en lista Excell';return true\"\r\n");
      out.write("       onMouseOut=\"window.status=' '\"><img alt=\"Consulta Offline en Lista Excell\" src=\"images/excell.gif\"\r\n");
      out.write("                                           border=\"0\"></A></td>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    </table>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t</center>\r\n");
      out.write("</form>\r\n");
}
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"10\" class=\"Fondoverdederecha\">&nbsp;</td>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</TBODY>\r\n");
      out.write("</TABLE>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "pie.jsp", out, true);
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<!--Scripts para los calendarios-->\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("    setPath('");
      out.print(request.getContextPath());
      out.write("');\r\n");
      out.write("    var calendario1 = new calendar1(document.theForm.FechaInicial);\r\n");
      out.write("    var calendario2 = new calendar1(document.theForm.FechaFinal);\r\n");
      out.write("    var calendario3 = new calendar1(document.theForm.FechaInicialOp);\r\n");
      out.write("    var calendario4 = new calendar1(document.theForm.FechaFinalOp);\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");

	} catch (Exception e) {
		System.out.println("Error en Consulta.jsp--->" + e);
	}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_logic_005fempty_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_logic_005fiterate_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  logic:empty
    org.apache.struts.taglib.logic.EmptyTag _jspx_th_logic_005fempty_005f0 = (org.apache.struts.taglib.logic.EmptyTag) _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname.get(org.apache.struts.taglib.logic.EmptyTag.class);
    boolean _jspx_th_logic_005fempty_005f0_reused = false;
    try {
      _jspx_th_logic_005fempty_005f0.setPageContext(_jspx_page_context);
      _jspx_th_logic_005fempty_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fiterate_005f0);
      // /menu.jsp(67,1) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fempty_005f0.setName("link");
      // /menu.jsp(67,1) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fempty_005f0.setProperty("idPadre");
      int _jspx_eval_logic_005fempty_005f0 = _jspx_th_logic_005fempty_005f0.doStartTag();
      if (_jspx_eval_logic_005fempty_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t<TR>\r\n");
          out.write("\t\t\t<TD valign=\"top\">\r\n");
          out.write("\t\t\t\t&nbsp;\r\n");
          out.write("\t\t\t</TD>\r\n");
          out.write("\t\t\t<TD colSpan=3 valign=\"top\" class=\"itemmenubold\">\r\n");
          out.write("\t\t\t\t<BR />\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_fmt_005fmessage_005f0(_jspx_th_logic_005fempty_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t</TD>\r\n");
          out.write("\t\t</TR>\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_logic_005fempty_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_logic_005fempty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname.reuse(_jspx_th_logic_005fempty_005f0);
      _jspx_th_logic_005fempty_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fempty_005f0, _jsp_getInstanceManager(), _jspx_th_logic_005fempty_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_logic_005fempty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f0_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fempty_005f0);
      int _jspx_eval_fmt_005fmessage_005f0 = _jspx_th_fmt_005fmessage_005f0.doStartTag();
      if (_jspx_eval_fmt_005fmessage_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_fmt_005fmessage_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_fmt_005fmessage_005f0);
        }
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t");
          if (_jspx_meth_bean_005fwrite_005f0(_jspx_th_fmt_005fmessage_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_fmt_005fmessage_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_fmt_005fmessage_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_fmt_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage.reuse(_jspx_th_fmt_005fmessage_005f0);
      _jspx_th_fmt_005fmessage_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_bean_005fwrite_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fmessage_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:write
    org.apache.struts.taglib.bean.WriteTag _jspx_th_bean_005fwrite_005f0 = (org.apache.struts.taglib.bean.WriteTag) _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.get(org.apache.struts.taglib.bean.WriteTag.class);
    boolean _jspx_th_bean_005fwrite_005f0_reused = false;
    try {
      _jspx_th_bean_005fwrite_005f0.setPageContext(_jspx_page_context);
      _jspx_th_bean_005fwrite_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fmessage_005f0);
      // /menu.jsp(75,5) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fwrite_005f0.setProperty("descripcion");
      // /menu.jsp(75,5) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fwrite_005f0.setName("link");
      int _jspx_eval_bean_005fwrite_005f0 = _jspx_th_bean_005fwrite_005f0.doStartTag();
      if (_jspx_th_bean_005fwrite_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.reuse(_jspx_th_bean_005fwrite_005f0);
      _jspx_th_bean_005fwrite_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_bean_005fwrite_005f0, _jsp_getInstanceManager(), _jspx_th_bean_005fwrite_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_bean_005fwrite_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_logic_005fnotEmpty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:write
    org.apache.struts.taglib.bean.WriteTag _jspx_th_bean_005fwrite_005f1 = (org.apache.struts.taglib.bean.WriteTag) _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.get(org.apache.struts.taglib.bean.WriteTag.class);
    boolean _jspx_th_bean_005fwrite_005f1_reused = false;
    try {
      _jspx_th_bean_005fwrite_005f1.setPageContext(_jspx_page_context);
      _jspx_th_bean_005fwrite_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fnotEmpty_005f0);
      // /menu.jsp(92,57) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fwrite_005f1.setProperty("accion");
      // /menu.jsp(92,57) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fwrite_005f1.setName("link");
      int _jspx_eval_bean_005fwrite_005f1 = _jspx_th_bean_005fwrite_005f1.doStartTag();
      if (_jspx_th_bean_005fwrite_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.reuse(_jspx_th_bean_005fwrite_005f1);
      _jspx_th_bean_005fwrite_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_bean_005fwrite_005f1, _jsp_getInstanceManager(), _jspx_th_bean_005fwrite_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_bean_005fwrite_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_logic_005fnotEmpty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:write
    org.apache.struts.taglib.bean.WriteTag _jspx_th_bean_005fwrite_005f2 = (org.apache.struts.taglib.bean.WriteTag) _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.get(org.apache.struts.taglib.bean.WriteTag.class);
    boolean _jspx_th_bean_005fwrite_005f2_reused = false;
    try {
      _jspx_th_bean_005fwrite_005f2.setPageContext(_jspx_page_context);
      _jspx_th_bean_005fwrite_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fnotEmpty_005f0);
      // /menu.jsp(92,105) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fwrite_005f2.setProperty("metodo");
      // /menu.jsp(92,105) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fwrite_005f2.setName("link");
      int _jspx_eval_bean_005fwrite_005f2 = _jspx_th_bean_005fwrite_005f2.doStartTag();
      if (_jspx_th_bean_005fwrite_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.reuse(_jspx_th_bean_005fwrite_005f2);
      _jspx_th_bean_005fwrite_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_bean_005fwrite_005f2, _jsp_getInstanceManager(), _jspx_th_bean_005fwrite_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_logic_005fnotEmpty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f1_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fnotEmpty_005f0);
      int _jspx_eval_fmt_005fmessage_005f1 = _jspx_th_fmt_005fmessage_005f1.doStartTag();
      if (_jspx_eval_fmt_005fmessage_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_fmt_005fmessage_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_fmt_005fmessage_005f1);
        }
        do {
          if (_jspx_meth_bean_005fwrite_005f3(_jspx_th_fmt_005fmessage_005f1, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_fmt_005fmessage_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_fmt_005fmessage_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_fmt_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage.reuse(_jspx_th_fmt_005fmessage_005f1);
      _jspx_th_fmt_005fmessage_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_bean_005fwrite_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fmessage_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:write
    org.apache.struts.taglib.bean.WriteTag _jspx_th_bean_005fwrite_005f3 = (org.apache.struts.taglib.bean.WriteTag) _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.get(org.apache.struts.taglib.bean.WriteTag.class);
    boolean _jspx_th_bean_005fwrite_005f3_reused = false;
    try {
      _jspx_th_bean_005fwrite_005f3.setPageContext(_jspx_page_context);
      _jspx_th_bean_005fwrite_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fmessage_005f1);
      // /menu.jsp(93,47) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fwrite_005f3.setProperty("descripcion");
      // /menu.jsp(93,47) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fwrite_005f3.setName("link");
      int _jspx_eval_bean_005fwrite_005f3 = _jspx_th_bean_005fwrite_005f3.doStartTag();
      if (_jspx_th_bean_005fwrite_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.reuse(_jspx_th_bean_005fwrite_005f3);
      _jspx_th_bean_005fwrite_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_bean_005fwrite_005f3, _jsp_getInstanceManager(), _jspx_th_bean_005fwrite_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_logic_005fnotEmpty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f2 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f2_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f2.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fnotEmpty_005f0);
      int _jspx_eval_fmt_005fmessage_005f2 = _jspx_th_fmt_005fmessage_005f2.doStartTag();
      if (_jspx_eval_fmt_005fmessage_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_fmt_005fmessage_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_fmt_005fmessage_005f2);
        }
        do {
          if (_jspx_meth_bean_005fwrite_005f4(_jspx_th_fmt_005fmessage_005f2, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_fmt_005fmessage_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_fmt_005fmessage_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_fmt_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage.reuse(_jspx_th_fmt_005fmessage_005f2);
      _jspx_th_fmt_005fmessage_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f2, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_bean_005fwrite_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fmessage_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:write
    org.apache.struts.taglib.bean.WriteTag _jspx_th_bean_005fwrite_005f4 = (org.apache.struts.taglib.bean.WriteTag) _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.get(org.apache.struts.taglib.bean.WriteTag.class);
    boolean _jspx_th_bean_005fwrite_005f4_reused = false;
    try {
      _jspx_th_bean_005fwrite_005f4.setPageContext(_jspx_page_context);
      _jspx_th_bean_005fwrite_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fmessage_005f2);
      // /menu.jsp(95,19) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fwrite_005f4.setProperty("descripcion");
      // /menu.jsp(95,19) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fwrite_005f4.setName("link");
      int _jspx_eval_bean_005fwrite_005f4 = _jspx_th_bean_005fwrite_005f4.doStartTag();
      if (_jspx_th_bean_005fwrite_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.reuse(_jspx_th_bean_005fwrite_005f4);
      _jspx_th_bean_005fwrite_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_bean_005fwrite_005f4, _jsp_getInstanceManager(), _jspx_th_bean_005fwrite_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f3 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f3_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f3.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f3.setParent(null);
      // /menu.jsp(119,33) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f3.setKey("javascript.menu.salir_app");
      int _jspx_eval_fmt_005fmessage_005f3 = _jspx_th_fmt_005fmessage_005f3.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f3);
      _jspx_th_fmt_005fmessage_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f3, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f4 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f4_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f4.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f4.setParent(null);
      // /menu.jsp(121,5) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f4.setKey("texto.menu.salir");
      int _jspx_eval_fmt_005fmessage_005f4 = _jspx_th_fmt_005fmessage_005f4.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f4);
      _jspx_th_fmt_005fmessage_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f4, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f4_reused);
    }
    return false;
  }
}
