/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.4
 * Generated at: 2018-06-08 09:53:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Vector;
import java.util.Enumeration;
import java.io.*;
import java.util.Vector;
import java.util.Enumeration;
import es.gateway.sesiones.obj.Grupo;
import es.portanode.util.Singleton;
import es.portanode.util.operadores.OperadorMultipleBeanCollection;
import es.portanode.util.operadores.OperadorMultipleBean;
import es.portanode.util.html.SesionConectada;

public final class ResultadoCerrar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("jar:file:/C:/Users/x45558re/Desktop/entorno/tomcat-9.0/tomcat-9.0.4/wtpwebapps/GatewayRamaEstable/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098703890000L));
    _jspx_dependants.put("/cabeceraLogo.jsp", Long.valueOf(1528450505192L));
    _jspx_dependants.put("/WEB-INF/tld/struts-bean.tld", Long.valueOf(1528450506029L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1528450505299L));
    _jspx_dependants.put("/menu.jsp", Long.valueOf(1528450525562L));
    _jspx_dependants.put("/WEB-INF/tld/fmt.tld", Long.valueOf(1528450506098L));
    _jspx_dependants.put("/WEB-INF/tld/struts-logic.tld", Long.valueOf(1528450505979L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("es.portanode.util.html.SesionConectada");
    _jspx_imports_classes.add("java.util.Vector");
    _jspx_imports_classes.add("java.util.Enumeration");
    _jspx_imports_classes.add("es.portanode.util.operadores.OperadorMultipleBeanCollection");
    _jspx_imports_classes.add("es.gateway.sesiones.obj.Grupo");
    _jspx_imports_classes.add("es.portanode.util.Singleton");
    _jspx_imports_classes.add("es.portanode.util.operadores.OperadorMultipleBean");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fbean_005fdefine_0026_005ftype_005fscope_005fname_005fid_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flogic_005fiterate_0026_005ftype_005fname_005findexId_005fid;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fmessage;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fbean_005fdefine_0026_005ftype_005fscope_005fname_005fid_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flogic_005fiterate_0026_005ftype_005fname_005findexId_005fid = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fmessage = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fbean_005fdefine_0026_005ftype_005fscope_005fname_005fid_005fnobody.release();
    _005fjspx_005ftagPool_005flogic_005fiterate_0026_005ftype_005fname_005findexId_005fid.release();
    _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname.release();
    _005fjspx_005ftagPool_005ffmt_005fmessage.release();
    _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.release();
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Operador</title>\r\n");
      out.write("<script language=\"JavaScript\" src=\"js/util.js\"></script>\r\n");
      out.write("<link href=\"estilos/estilos.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body leftMargin=0 topMargin=0 marginheight=\"0\" marginwidth=\"0\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    String anterior = (String) request.getAttribute("Anterior");

    String subtitulo1=new String("Cerrar Proceso Expirado");

      out.write("\r\n");
      out.write("\r\n");
      out.write("  ");
      out.write("<!-- Insercion de Cabecera -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/ComprobarSesion", out, false);
      out.write("\r\n");
      out.write("  ");


      SesionConectada cs2 = new SesionConectada(request);
      String operadorSesion = cs2.GetOperador();
      System.out.println("cabeceraLogo: oper sera "+cs2.GetOperador());

      String imagen = operadorSesion;
      if(imagen==null)
      {
        imagen = (String) request.getAttribute("OperadorConexion");
      }
      if(imagen==null)
      {
         imagen = (String) request.getAttribute("OperadorConectado");
      }
      if(imagen==null)
      {
          imagen="";
      }

      /*
        String imagen = (String) request.getAttribute("OperadorConexion");
        if(imagen==null) imagen = (String) request.getAttribute("OperadorConectado");
        if(imagen==null)  imagen="";
        */
    String logo = "";
    if ((imagen==null)||(imagen.equals(""))){
       logo = "<img src='images/telefono.jpg' name='logotipo' width='90' height='56'>";
    }
    else{
       logo = "<img src='images/"+imagen+".gif' name='logotipo' ALT='Operador' height='56'>";
    }
    boolean isAdmin = false;
    String esAdmin=(String)request.getAttribute("isAdmin");
    if ("true".equals(esAdmin)){
      isAdmin = true;
    }
    String nombreServlet = getServletConfig().getServletName();


      String usuarioCabecera = cs2.GetSuserId();
      System.out.println(usuarioCabecera);
      OperadorMultipleBeanCollection mOperadoresCabecera = new OperadorMultipleBeanCollection (null,usuarioCabecera );
      Vector vOperadoresCabecera = mOperadoresCabecera.getMultiOperador ( );
      int totalOperadoresCabecera = vOperadoresCabecera.size();

      Vector vGrupos = (Vector)session.getAttribute("grupos");
      String grupoActivo = (String)session.getAttribute("grupoActivo");      

  
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/ventana-modal-1.3.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/abrir-ventana-alertas.js\"></script>\r\n");
      out.write("<link href=\"estilos/ventana-modal.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("    //Función que permite abrir el fichero de ayuda correspondiente a la página.\r\n");
      out.write("    function ayuda()\r\n");
      out.write("    {\r\n");
      out.write("        var p = '");
      out.print(nombreServlet);
      out.write("';\r\n");
      out.write("        window.open('ayuda/' + p + '.htm', 'AYUDA', 'toolbar=no,location=no,directories=no,status=no,menubar=no,resizable=yes,scrollbars=yes,width=750');\r\n");
      out.write("    }\r\n");
      out.write("    function CambioOper()\r\n");
      out.write("    {\r\n");
      out.write("        f = document.formularioCabecera;\r\n");
      out.write("        f.action = \"CambioOperadorSesion\";\r\n");
      out.write("        f.submit();\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function CambioGrupo(){\r\n");
      out.write("        f = document.formularioCabecera;\r\n");
      out.write("        f.action = \"CambioGrupoSesion\";\r\n");
      out.write("        f.submit();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<!-- Fin Insercion de Cabecera -->\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" height=\"56\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"40%\" class='celdalineaabajo'>");
      out.print(logo);
      out.write("</td>\r\n");
      out.write("    <td width=\"20%\" class='celdalineaabajo' colspan=\"2\" align=\"center\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr><td align=\"center\"><img src='images/portanode.png' name='logotipo' ALT='Operador'></td></tr>\r\n");
      out.write("           \t<tr><td>&nbsp;</td></tr>\r\n");
      out.write("        </table>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td width=\"40%\" align=\"right\" class='celdalineaabajo' valign=\"center\">\r\n");
      out.write("      <table border=\"0\">\r\n");
      out.write("       <tr>\r\n");
      out.write("         <td align=\"right\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<font class=\"texto3\">subtitulo1</font>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("         </td>\r\n");
      out.write("       </tr>\r\n");
      out.write("       <tr>\r\n");
      out.write("         <td align=\"right\">\r\n");
      out.write("           <a  href=\"javascript:ayuda()\"><img src=\"images/help.gif\" alt=\"Manual de usuario\" border=\"0\"></a>\r\n");
      out.write("         </td>\r\n");
      out.write("       </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>");
      out.write("\r\n");
      out.write("        <script language=\"JavaScript\">\r\n");
      out.write("        var tabla=\"<table width='100%' height='100%' border='0' cellpadding='0' cellspacing='0'>\";\r\n");
      out.write("        document.write(tabla);\r\n");
      out.write("        </script>\r\n");
      out.write("          <TBODY>\r\n");
      out.write("          <TR>\r\n");
      out.write("            <td width=\"10\" class=\"Fondoverdederecha\">\r\n");
      out.write("               &nbsp;\r\n");
      out.write("            </td>\r\n");
      out.write("            <TD vAlign=top width=\"180\" class=\"celdalineaderecha\">\r\n");
      out.write("              ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String fechaSistema = (String) request.getAttribute("FechaSistema");
 System.out.println(fechaSistema);
 

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("\t\t//Función que permite abrir el fichero de ayuda correspondiente a la página\r\n");
      out.write("\r\n");
      out.write("\t\tfunction lanzaFormularioDe3(accionName, metodo, numForm){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(accionName==\"MenuOpcionesUsuario\"){\r\n");
      out.write("\t\t\t\tf = document.MenuOpcionesUsuario;\r\n");
      out.write("\t\t\t\tf.accion.value = metodo;\r\n");
      out.write("\t\t\t}else if(accionName==\"ConsultaExpirados\"){\r\n");
      out.write("\t\t\t\tf = document.Generico;\r\n");
      out.write("\t\t\t\tf.Accion.value = metodo;\r\n");
      out.write("                f.action = accionName;\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tf = document.Generico;\r\n");
      out.write("\t\t\t\tf.action = accionName;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tf.submit();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction lanzaFormularioDe2(accionName){\r\n");
      out.write("\t\t\tf = document.Generico;\r\n");
      out.write("\t\t\tf.action = accionName;\r\n");
      out.write("\t\t\tf.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction lanzaSalir(formName, accionName){\r\n");
      out.write("\t\t\tf = document.forms[formName];\r\n");
      out.write("\t\t\tf.accion.value = accionName;\r\n");
      out.write("\t\t\tf.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction lanzaModuloUsuarios(accionName){\r\n");
      out.write("\t\t\tf = document.MenuOpcionesUsuario;\r\n");
      out.write("\t\t\tf.accion.value = accionName;\r\n");
      out.write("\t\t\tf.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      //  bean:define
      org.apache.struts.taglib.bean.DefineTag _jspx_th_bean_005fdefine_005f0 = (org.apache.struts.taglib.bean.DefineTag) _005fjspx_005ftagPool_005fbean_005fdefine_0026_005ftype_005fscope_005fname_005fid_005fnobody.get(org.apache.struts.taglib.bean.DefineTag.class);
      boolean _jspx_th_bean_005fdefine_005f0_reused = false;
      try {
        _jspx_th_bean_005fdefine_005f0.setPageContext(_jspx_page_context);
        _jspx_th_bean_005fdefine_005f0.setParent(null);
        // /menu.jsp(52,0) name = id type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_bean_005fdefine_005f0.setId("permisosLink");
        // /menu.jsp(52,0) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_bean_005fdefine_005f0.setType("java.util.ArrayList");
        // /menu.jsp(52,0) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_bean_005fdefine_005f0.setName("links");
        // /menu.jsp(52,0) name = scope type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_bean_005fdefine_005f0.setScope("session");
        int _jspx_eval_bean_005fdefine_005f0 = _jspx_th_bean_005fdefine_005f0.doStartTag();
        if (_jspx_th_bean_005fdefine_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fbean_005fdefine_0026_005ftype_005fscope_005fname_005fid_005fnobody.reuse(_jspx_th_bean_005fdefine_005f0);
        _jspx_th_bean_005fdefine_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_bean_005fdefine_005f0, _jsp_getInstanceManager(), _jspx_th_bean_005fdefine_005f0_reused);
      }
      java.util.ArrayList permisosLink = null;
      permisosLink = (java.util.ArrayList) _jspx_page_context.findAttribute("permisosLink");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table cellSpacing=0 cellPadding=0 border=0 width=\"100%\">\r\n");
      out.write("    <FORM METHOD=POST ACTION=\"MenuPrincipal\" name=\"Generico\">\r\n");
      out.write("       <INPUT TYPE=\"hidden\" name=\"OperadorConexion\" value=\"");
      out.print(imagen);
      out.write("\">\r\n");
      out.write("       <INPUT TYPE=\"hidden\" name=\"OperadorConectado\" value=\"");
      out.print(imagen);
      out.write("\">\r\n");
      out.write("       <INPUT TYPE=\"hidden\" NAME=\"Posicion\" VALUE=\"1\">\r\n");
      out.write("       <INPUT TYPE=\"hidden\" NAME=\"Fecha\" VALUE=\"");
      out.print(fechaSistema);
      out.write("\">\r\n");
      out.write("       <INPUT TYPE=\"hidden\" NAME=\"Accion\" VALUE=\"\">\r\n");
      out.write("    </form>\r\n");
      out.write("    <form method=post action=\"MenuOpcionesUsuario.do\" name=\"MenuOpcionesUsuario\"> \r\n");
      out.write("    <input type=\"hidden\" name=\"accion\" value=\"\">\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      //  logic:iterate
      org.apache.struts.taglib.logic.IterateTag _jspx_th_logic_005fiterate_005f0 = (org.apache.struts.taglib.logic.IterateTag) _005fjspx_005ftagPool_005flogic_005fiterate_0026_005ftype_005fname_005findexId_005fid.get(org.apache.struts.taglib.logic.IterateTag.class);
      boolean _jspx_th_logic_005fiterate_005f0_reused = false;
      try {
        _jspx_th_logic_005fiterate_005f0.setPageContext(_jspx_page_context);
        _jspx_th_logic_005fiterate_005f0.setParent(null);
        // /menu.jsp(66,0) name = id type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_logic_005fiterate_005f0.setId("link");
        // /menu.jsp(66,0) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_logic_005fiterate_005f0.setName("permisosLink");
        // /menu.jsp(66,0) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_logic_005fiterate_005f0.setType("es.gateway.sesiones.permisos.bean.LinkBean");
        // /menu.jsp(66,0) name = indexId type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_logic_005fiterate_005f0.setIndexId("ij");
        int _jspx_eval_logic_005fiterate_005f0 = _jspx_th_logic_005fiterate_005f0.doStartTag();
        if (_jspx_eval_logic_005fiterate_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          es.gateway.sesiones.permisos.bean.LinkBean link = null;
          java.lang.Integer ij = null;
          if (_jspx_eval_logic_005fiterate_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_logic_005fiterate_005f0);
          }
          link = (es.gateway.sesiones.permisos.bean.LinkBean) _jspx_page_context.findAttribute("link");
          ij = (java.lang.Integer) _jspx_page_context.findAttribute("ij");
          do {
            out.write('\r');
            out.write('\n');
            out.write('	');
            if (_jspx_meth_logic_005fempty_005f0(_jspx_th_logic_005fiterate_005f0, _jspx_page_context))
              return;
            out.write('\r');
            out.write('\n');
            out.write('	');
            //  logic:notEmpty
            org.apache.struts.taglib.logic.NotEmptyTag _jspx_th_logic_005fnotEmpty_005f0 = (org.apache.struts.taglib.logic.NotEmptyTag) _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.get(org.apache.struts.taglib.logic.NotEmptyTag.class);
            boolean _jspx_th_logic_005fnotEmpty_005f0_reused = false;
            try {
              _jspx_th_logic_005fnotEmpty_005f0.setPageContext(_jspx_page_context);
              _jspx_th_logic_005fnotEmpty_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fiterate_005f0);
              // /menu.jsp(80,1) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_logic_005fnotEmpty_005f0.setName("link");
              // /menu.jsp(80,1) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_logic_005fnotEmpty_005f0.setProperty("idPadre");
              int _jspx_eval_logic_005fnotEmpty_005f0 = _jspx_th_logic_005fnotEmpty_005f0.doStartTag();
              if (_jspx_eval_logic_005fnotEmpty_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("\t\t<TR onMouseOver=\"this.className='Fondoverdeover'\" onMouseOut=\"this.className='Fondoblanco'\">\r\n");
                  out.write("\r\n");
                  out.write("\r\n");
                  out.write("\t\t\t\t<input type=\"hidden\" name=\"accion\" value=\"\">\r\n");
                  out.write("\r\n");
                  out.write("\t\t\t\t<TD valign=\"top\">&nbsp;</TD>\r\n");
                  out.write("\t\t\t\t<TD width=6 valign=\"top\">&nbsp;</TD>\r\n");
                  out.write("\t\t\t\t<TD width=172 colspan=\"2\">\r\n");
                  out.write("\t\t\t\t");
for (int i=0;i<link.getNivel().intValue()-2;i++){ out.print("&nbsp");}
                  out.write("\r\n");
                  out.write("\t\t\t\t\t<IMG height=9 src=\"images/cuadro.gif\" width=9 alt=\"->\"> \r\n");
                  out.write("\t\t\t\t\t\r\n");
                  out.write("\t\t\t\t\t<a href=\"#\" onclick=\"javascript:lanzaFormularioDe3('");
                  if (_jspx_meth_bean_005fwrite_005f1(_jspx_th_logic_005fnotEmpty_005f0, _jspx_page_context))
                    return;
                  out.write("', '");
                  if (_jspx_meth_bean_005fwrite_005f2(_jspx_th_logic_005fnotEmpty_005f0, _jspx_page_context))
                    return;
                  out.write("', '");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ij}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("')\" \r\n");
                  out.write("\t\t\t\t\t\tonMouseOver=\"window.status='");
                  if (_jspx_meth_fmt_005fmessage_005f1(_jspx_th_logic_005fnotEmpty_005f0, _jspx_page_context))
                    return;
                  out.write("';return true\"\r\n");
                  out.write("\t\t\t\t\t\tonMouseOut=\"window.status=' '\" class=\"itemmenu\">\r\n");
                  out.write("\t\t\t\t\t\t");
                  if (_jspx_meth_fmt_005fmessage_005f2(_jspx_th_logic_005fnotEmpty_005f0, _jspx_page_context))
                    return;
                  out.write("\r\n");
                  out.write("\t\t\t\t\t</a>\r\n");
                  out.write("\t\t\t\t</TD>\r\n");
                  out.write("\t\t</TR>\r\n");
                  out.write("\t");
                  int evalDoAfterBody = _jspx_th_logic_005fnotEmpty_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_logic_005fnotEmpty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.reuse(_jspx_th_logic_005fnotEmpty_005f0);
              _jspx_th_logic_005fnotEmpty_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fnotEmpty_005f0, _jsp_getInstanceManager(), _jspx_th_logic_005fnotEmpty_005f0_reused);
            }
            out.write('\r');
            out.write('\n');
            int evalDoAfterBody = _jspx_th_logic_005fiterate_005f0.doAfterBody();
            link = (es.gateway.sesiones.permisos.bean.LinkBean) _jspx_page_context.findAttribute("link");
            ij = (java.lang.Integer) _jspx_page_context.findAttribute("ij");
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_logic_005fiterate_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
          }
        }
        if (_jspx_th_logic_005fiterate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005flogic_005fiterate_0026_005ftype_005fname_005findexId_005fid.reuse(_jspx_th_logic_005fiterate_005f0);
        _jspx_th_logic_005fiterate_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fiterate_005f0, _jsp_getInstanceManager(), _jspx_th_logic_005fiterate_005f0_reused);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<TR>\r\n");
      out.write("\t\t<TD valign=\"top\">&nbsp;</TD>\r\n");
      out.write("\t\t<TD colSpan=3 valign=\"top\" class=\"itemmenubold\">\r\n");
      out.write("\t\t\t<br>&nbsp;</BR>\r\n");
      out.write("\t\t</TD>\r\n");
      out.write("\t</TR>\r\n");
      out.write("\r\n");
      out.write("    <TR onMouseOver=\"this.className='Fondoverdeover'\" onMouseOut=\"this.className='Fondoblanco'\">\r\n");
      out.write("\t\t <form method=post action=\"MenuSalir.do\" name=\"MenuSalirForm\"> \r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"accion\" value=\"salir\"> \r\n");
      out.write("\t\t\t<TD valign=\"top\">&nbsp;</TD>\r\n");
      out.write("\t\t\t<TD width=6 valign=\"top\">&nbsp;</TD>\r\n");
      out.write("\t\t\t<TD width=12>\r\n");
      out.write("\t\t\t\t<IMG height=9 src=\"images/cuadro.gif\" width=9 alt=\"->\">\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t        <TD width=160>\r\n");
      out.write("\t\t\t\t<A href=\"#\" onclick=\"javascript:lanzaSalir('MenuSalirForm', 'salir')\"\r\n");
      out.write("\t\t\t\t\tonMouseOver=\"window.status='");
      if (_jspx_meth_fmt_005fmessage_005f3(_jspx_page_context))
        return;
      out.write("';return true\"\r\n");
      out.write("\t\t\t\t\tonMouseOut=\"window.status=' '\" class=\"itemmenu\">\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_fmt_005fmessage_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t </FORM> \r\n");
      out.write("\t</TR>\r\n");
      out.write("\r\n");
      out.write("</table>");
      out.write("\r\n");
      out.write("            </TD><!-- InstanceBeginEditable name=\"contenido\" -->\r\n");
      out.write("            <TD class=Titulo vAlign=top align=middle background=\"images/fondocentro.gif\">\r\n");
      out.write("               <br>\r\n");
      out.write("               <DIV align=left class=\"Titulo\">&nbsp;&nbsp;&nbsp;<img src=\"images/flecha.gif\" border=\"0\"/>Envio solicitud</DIV>\r\n");
      out.write("\r\n");
      out.write("                  <FORM METHOD=POST ACTION=\"");
      out.print(anterior);
      out.write("\" name=\"fback\">\r\n");
      out.write("                    <INPUT TYPE=\"hidden\" name=\"OperadorConexion\" value=\"");
      out.print(imagen);
      out.write("\">\r\n");
      out.write("                    <INPUT TYPE=\"hidden\" name=\"Accion\" value=\"Cerrar\">\r\n");
      out.write("                  </FORM>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                  <CENTER>\r\n");
      out.write("                  <table align=\"center\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td align=\"center\" class=\"texto\">\r\n");
      out.write("                         <CENTER>\r\n");
      out.write("                          <br><br><br>\r\n");
      out.write("                           <table border=\"1\" class=\"tablas\">\r\n");
      out.write("                             <tr>\r\n");
      out.write("                                <td class=\"bgCabeceraFila\" align=\"center\">\r\n");
      out.write("                                   Resultado de la operación\r\n");
      out.write("                                </td>\r\n");
      out.write("                             </tr>\r\n");
      out.write("                             <tr>\r\n");
      out.write("                               <td class=\"bgFila\">\r\n");
      out.write("                                 <font class=\"texto\">");
      out.print(request.getAttribute("Mensaje"));
      out.write("</font>\r\n");
      out.write("                               </td>\r\n");
      out.write("                             </tr>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </CENTER>\r\n");
      out.write("                      </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td align=\"center\"><a href=\"javascript:history.back()//'\" onMouseOver=\"window.status='Pagina Anterior';return true\" onMouseOut=\"window.status=' '\"><img src=\"images/Back.jpg\" border=\"0\" width=\"107\" border=\"0\" height=\"28\"></a></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                  </table>\r\n");
      out.write("                </CENTER>\r\n");
      out.write("\r\n");
      out.write("             ");
      out.write("\r\n");
      out.write("              </td>\r\n");
      out.write("             <td width=\"10\" class=\"Fondoverdederecha\">\r\n");
      out.write("                &nbsp;\r\n");
      out.write("             </td>\r\n");
      out.write("          </TR>\r\n");
      out.write("        </TBODY>\r\n");
      out.write("    </TABLE>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "pie.jsp", out, true);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_logic_005fempty_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_logic_005fiterate_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  logic:empty
    org.apache.struts.taglib.logic.EmptyTag _jspx_th_logic_005fempty_005f0 = (org.apache.struts.taglib.logic.EmptyTag) _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname.get(org.apache.struts.taglib.logic.EmptyTag.class);
    boolean _jspx_th_logic_005fempty_005f0_reused = false;
    try {
      _jspx_th_logic_005fempty_005f0.setPageContext(_jspx_page_context);
      _jspx_th_logic_005fempty_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fiterate_005f0);
      // /menu.jsp(67,1) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fempty_005f0.setName("link");
      // /menu.jsp(67,1) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fempty_005f0.setProperty("idPadre");
      int _jspx_eval_logic_005fempty_005f0 = _jspx_th_logic_005fempty_005f0.doStartTag();
      if (_jspx_eval_logic_005fempty_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t<TR>\r\n");
          out.write("\t\t\t<TD valign=\"top\">\r\n");
          out.write("\t\t\t\t&nbsp;\r\n");
          out.write("\t\t\t</TD>\r\n");
          out.write("\t\t\t<TD colSpan=3 valign=\"top\" class=\"itemmenubold\">\r\n");
          out.write("\t\t\t\t<BR />\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_fmt_005fmessage_005f0(_jspx_th_logic_005fempty_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t</TD>\r\n");
          out.write("\t\t</TR>\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_logic_005fempty_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_logic_005fempty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname.reuse(_jspx_th_logic_005fempty_005f0);
      _jspx_th_logic_005fempty_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fempty_005f0, _jsp_getInstanceManager(), _jspx_th_logic_005fempty_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_logic_005fempty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f0_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fempty_005f0);
      int _jspx_eval_fmt_005fmessage_005f0 = _jspx_th_fmt_005fmessage_005f0.doStartTag();
      if (_jspx_eval_fmt_005fmessage_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_fmt_005fmessage_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_fmt_005fmessage_005f0);
        }
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t");
          if (_jspx_meth_bean_005fwrite_005f0(_jspx_th_fmt_005fmessage_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_fmt_005fmessage_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_fmt_005fmessage_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_fmt_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage.reuse(_jspx_th_fmt_005fmessage_005f0);
      _jspx_th_fmt_005fmessage_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_bean_005fwrite_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fmessage_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:write
    org.apache.struts.taglib.bean.WriteTag _jspx_th_bean_005fwrite_005f0 = (org.apache.struts.taglib.bean.WriteTag) _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.get(org.apache.struts.taglib.bean.WriteTag.class);
    boolean _jspx_th_bean_005fwrite_005f0_reused = false;
    try {
      _jspx_th_bean_005fwrite_005f0.setPageContext(_jspx_page_context);
      _jspx_th_bean_005fwrite_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fmessage_005f0);
      // /menu.jsp(75,5) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fwrite_005f0.setProperty("descripcion");
      // /menu.jsp(75,5) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fwrite_005f0.setName("link");
      int _jspx_eval_bean_005fwrite_005f0 = _jspx_th_bean_005fwrite_005f0.doStartTag();
      if (_jspx_th_bean_005fwrite_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.reuse(_jspx_th_bean_005fwrite_005f0);
      _jspx_th_bean_005fwrite_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_bean_005fwrite_005f0, _jsp_getInstanceManager(), _jspx_th_bean_005fwrite_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_bean_005fwrite_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_logic_005fnotEmpty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:write
    org.apache.struts.taglib.bean.WriteTag _jspx_th_bean_005fwrite_005f1 = (org.apache.struts.taglib.bean.WriteTag) _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.get(org.apache.struts.taglib.bean.WriteTag.class);
    boolean _jspx_th_bean_005fwrite_005f1_reused = false;
    try {
      _jspx_th_bean_005fwrite_005f1.setPageContext(_jspx_page_context);
      _jspx_th_bean_005fwrite_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fnotEmpty_005f0);
      // /menu.jsp(92,57) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fwrite_005f1.setProperty("accion");
      // /menu.jsp(92,57) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fwrite_005f1.setName("link");
      int _jspx_eval_bean_005fwrite_005f1 = _jspx_th_bean_005fwrite_005f1.doStartTag();
      if (_jspx_th_bean_005fwrite_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.reuse(_jspx_th_bean_005fwrite_005f1);
      _jspx_th_bean_005fwrite_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_bean_005fwrite_005f1, _jsp_getInstanceManager(), _jspx_th_bean_005fwrite_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_bean_005fwrite_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_logic_005fnotEmpty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:write
    org.apache.struts.taglib.bean.WriteTag _jspx_th_bean_005fwrite_005f2 = (org.apache.struts.taglib.bean.WriteTag) _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.get(org.apache.struts.taglib.bean.WriteTag.class);
    boolean _jspx_th_bean_005fwrite_005f2_reused = false;
    try {
      _jspx_th_bean_005fwrite_005f2.setPageContext(_jspx_page_context);
      _jspx_th_bean_005fwrite_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fnotEmpty_005f0);
      // /menu.jsp(92,105) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fwrite_005f2.setProperty("metodo");
      // /menu.jsp(92,105) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fwrite_005f2.setName("link");
      int _jspx_eval_bean_005fwrite_005f2 = _jspx_th_bean_005fwrite_005f2.doStartTag();
      if (_jspx_th_bean_005fwrite_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.reuse(_jspx_th_bean_005fwrite_005f2);
      _jspx_th_bean_005fwrite_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_bean_005fwrite_005f2, _jsp_getInstanceManager(), _jspx_th_bean_005fwrite_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_logic_005fnotEmpty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f1_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fnotEmpty_005f0);
      int _jspx_eval_fmt_005fmessage_005f1 = _jspx_th_fmt_005fmessage_005f1.doStartTag();
      if (_jspx_eval_fmt_005fmessage_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_fmt_005fmessage_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_fmt_005fmessage_005f1);
        }
        do {
          if (_jspx_meth_bean_005fwrite_005f3(_jspx_th_fmt_005fmessage_005f1, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_fmt_005fmessage_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_fmt_005fmessage_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_fmt_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage.reuse(_jspx_th_fmt_005fmessage_005f1);
      _jspx_th_fmt_005fmessage_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_bean_005fwrite_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fmessage_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:write
    org.apache.struts.taglib.bean.WriteTag _jspx_th_bean_005fwrite_005f3 = (org.apache.struts.taglib.bean.WriteTag) _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.get(org.apache.struts.taglib.bean.WriteTag.class);
    boolean _jspx_th_bean_005fwrite_005f3_reused = false;
    try {
      _jspx_th_bean_005fwrite_005f3.setPageContext(_jspx_page_context);
      _jspx_th_bean_005fwrite_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fmessage_005f1);
      // /menu.jsp(93,47) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fwrite_005f3.setProperty("descripcion");
      // /menu.jsp(93,47) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fwrite_005f3.setName("link");
      int _jspx_eval_bean_005fwrite_005f3 = _jspx_th_bean_005fwrite_005f3.doStartTag();
      if (_jspx_th_bean_005fwrite_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.reuse(_jspx_th_bean_005fwrite_005f3);
      _jspx_th_bean_005fwrite_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_bean_005fwrite_005f3, _jsp_getInstanceManager(), _jspx_th_bean_005fwrite_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_logic_005fnotEmpty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f2 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f2_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f2.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fnotEmpty_005f0);
      int _jspx_eval_fmt_005fmessage_005f2 = _jspx_th_fmt_005fmessage_005f2.doStartTag();
      if (_jspx_eval_fmt_005fmessage_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_fmt_005fmessage_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_fmt_005fmessage_005f2);
        }
        do {
          if (_jspx_meth_bean_005fwrite_005f4(_jspx_th_fmt_005fmessage_005f2, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_fmt_005fmessage_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_fmt_005fmessage_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_fmt_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage.reuse(_jspx_th_fmt_005fmessage_005f2);
      _jspx_th_fmt_005fmessage_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f2, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_bean_005fwrite_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fmessage_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:write
    org.apache.struts.taglib.bean.WriteTag _jspx_th_bean_005fwrite_005f4 = (org.apache.struts.taglib.bean.WriteTag) _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.get(org.apache.struts.taglib.bean.WriteTag.class);
    boolean _jspx_th_bean_005fwrite_005f4_reused = false;
    try {
      _jspx_th_bean_005fwrite_005f4.setPageContext(_jspx_page_context);
      _jspx_th_bean_005fwrite_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fmessage_005f2);
      // /menu.jsp(95,19) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fwrite_005f4.setProperty("descripcion");
      // /menu.jsp(95,19) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fwrite_005f4.setName("link");
      int _jspx_eval_bean_005fwrite_005f4 = _jspx_th_bean_005fwrite_005f4.doStartTag();
      if (_jspx_th_bean_005fwrite_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.reuse(_jspx_th_bean_005fwrite_005f4);
      _jspx_th_bean_005fwrite_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_bean_005fwrite_005f4, _jsp_getInstanceManager(), _jspx_th_bean_005fwrite_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f3 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f3_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f3.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f3.setParent(null);
      // /menu.jsp(119,33) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f3.setKey("javascript.menu.salir_app");
      int _jspx_eval_fmt_005fmessage_005f3 = _jspx_th_fmt_005fmessage_005f3.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f3);
      _jspx_th_fmt_005fmessage_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f3, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f4 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f4_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f4.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f4.setParent(null);
      // /menu.jsp(121,5) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f4.setKey("texto.menu.salir");
      int _jspx_eval_fmt_005fmessage_005f4 = _jspx_th_fmt_005fmessage_005f4.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f4);
      _jspx_th_fmt_005fmessage_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f4, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f4_reused);
    }
    return false;
  }
}
